### ISSUE TITLE
use case

### ISSUE THREAD

**Issue by kostyrev** [groks/ansible-repo-google#2]
Hello!
Could you please shed a light on use case of this role?
I want to have the latest chrome on my host. I find you role and... nothing.
You have some additional role built on top of this one? or what? why on earth would I want to enable google-chrome repo and not to install chrome. Don't get it.
Thanks!

**Comment by groks** [comment]
This is covered in the [README](https://github.com/groks/ansible-repo-google#repo-google): this role installs more than one Google repo, but even if it was just the Chrome repo, there are three versions of Chrome available:
- google-chrome-beta
- google-chrome-stable
- google-chrome-unstable

This role makes it possible to install a version of Chrome, but you need to choose which one you want and install it the usual way eg with the ansible _dnf_ module.

Merry Christmas!

**Comment by kostyrev** [comment]
Thanks for reply!
P.S. I'm a Russian and we don't celebrate Christmas on 25th of December.
